// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZggejllQd4RBV5o8npNN6_o5CTGrsshc',
    appId: '1:211140625825:web:0d7c89d801499df764b7e0',
    messagingSenderId: '211140625825',
    projectId: 'e-vigilance-67783',
    authDomain: 'e-vigilance-67783.firebaseapp.com',
    storageBucket: 'e-vigilance-67783.firebasestorage.app',
    measurementId: 'G-44VJLBBTF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9E2Yqg3wYRW5gIMee7vKWEy2I6l-pbEs',
    appId: '1:211140625825:android:c12dafa981fe103a64b7e0',
    messagingSenderId: '211140625825',
    projectId: 'e-vigilance-67783',
    storageBucket: 'e-vigilance-67783.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxaZTX5J4i1mGe-W7pOUjdHZ0eS-vzyxI',
    appId: '1:211140625825:ios:a1e9fe66b00e232464b7e0',
    messagingSenderId: '211140625825',
    projectId: 'e-vigilance-67783',
    storageBucket: 'e-vigilance-67783.firebasestorage.app',
    iosBundleId: 'com.example.evigilance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxaZTX5J4i1mGe-W7pOUjdHZ0eS-vzyxI',
    appId: '1:211140625825:ios:a1e9fe66b00e232464b7e0',
    messagingSenderId: '211140625825',
    projectId: 'e-vigilance-67783',
    storageBucket: 'e-vigilance-67783.firebasestorage.app',
    iosBundleId: 'com.example.evigilance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZggejllQd4RBV5o8npNN6_o5CTGrsshc',
    appId: '1:211140625825:web:677bdd1e916ec7b764b7e0',
    messagingSenderId: '211140625825',
    projectId: 'e-vigilance-67783',
    authDomain: 'e-vigilance-67783.firebaseapp.com',
    storageBucket: 'e-vigilance-67783.firebasestorage.app',
    measurementId: 'G-1JT4PXG3J2',
  );
}
